import { UserProfile, CastingCall, Conversation, Message, Application, CrewRole } from './types';

export const ALL_CREW_ROLES: CrewRole[] = [
  'Director',
  'Actor',
  'Cinematographer',
  'Editor',
  'Writer',
  'Sound Designer',
  'Lightman',
  'Producer',
  'Casting Director',
  'Production Designer',
  'Makeup Artist',
  'Costume Designer',
  'VFX Artist',
  'Choreographer',
  'Stunt Coordinator',
];

export const SAMPLE_PROFILES: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Arjun Mehta',
    role: 'talent',
    title: 'Lead Actor',
    crewRole: 'Actor',
    bio: 'Trained at FTII with 8 years of experience in feature films and OTT series. Specializing in dramatic and action roles.',
    skills: ['Acting', 'Action', 'Dance', 'Dialogue Delivery', 'Hindi', 'English'],
    experience: '8 years',
    experienceYears: 8,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://youtube.com/arjunmehta', 'https://vimeo.com/arjunreel'],
    profileImage: null,
    contactEmail: 'arjun@email.com',
    contactPhone: '+91 9876543210',
    isVerified: true,
    industryTypes: ['film', 'ott', 'web_series'],
    connections: ['user-4', 'user-5'],
    dayRate: 50000,
    rating: 4.8,
    reviewCount: 32,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Priya Sharma',
    role: 'talent',
    title: 'Cinematographer',
    crewRole: 'Cinematographer',
    bio: 'Award-winning cinematographer with a keen eye for visual storytelling. Worked on 15+ feature films and numerous ad campaigns.',
    skills: ['Cinematography', 'Lighting', 'Color Grading', 'Drone Operation', 'ARRI', 'RED'],
    experience: '12 years',
    experienceYears: 12,
    location: 'Delhi, India',
    availability: 'available',
    portfolioLinks: ['https://vimeo.com/priyasharma'],
    profileImage: null,
    contactEmail: 'priya.sharma@email.com',
    contactPhone: '+91 9876543211',
    isVerified: true,
    industryTypes: ['film', 'ad_film', 'music_video'],
    connections: ['user-4'],
    dayRate: 75000,
    rating: 4.9,
    reviewCount: 45,
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Rohan Kapoor',
    role: 'talent',
    title: 'Writer & Director',
    crewRole: 'Director',
    bio: 'Emerging filmmaker with 2 short films at international festivals. Looking for feature-length opportunities.',
    skills: ['Screenwriting', 'Direction', 'Editing', 'Story Development', 'Hindi', 'Urdu'],
    experience: '4 years',
    experienceYears: 4,
    location: 'Mumbai, India',
    availability: 'busy',
    portfolioLinks: ['https://drive.google.com/rohanscripts'],
    profileImage: null,
    contactEmail: 'rohan.k@email.com',
    contactPhone: '+91 9876543212',
    isVerified: false,
    industryTypes: ['film', 'web_series', 'theatre'],
    connections: [],
    dayRate: 35000,
    rating: 4.3,
    reviewCount: 8,
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Kavita Productions',
    role: 'producer',
    title: 'Production House',
    crewRole: 'Producer',
    bio: 'Leading production house behind 20+ acclaimed films. Currently developing a slate of OTT originals.',
    skills: ['Production', 'Financing', 'Distribution', 'Project Management'],
    experience: '18 years',
    experienceYears: 18,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://kavitaproductions.com'],
    profileImage: null,
    contactEmail: 'contact@kavitaprod.com',
    contactPhone: '+91 9876543213',
    isVerified: true,
    industryTypes: ['film', 'ott', 'web_series'],
    connections: ['user-1', 'user-2'],
    dayRate: 0,
    rating: 4.7,
    reviewCount: 60,
    createdAt: '2023-06-01T10:00:00Z',
  },
  {
    id: 'user-5',
    name: 'Neha Agarwal',
    role: 'casting_director',
    title: 'Casting Director',
    crewRole: 'Casting Director',
    bio: 'Cast for 30+ feature films and series. Known for discovering fresh talent and perfect casting choices.',
    skills: ['Casting', 'Talent Scouting', 'Audition Management', 'Negotiation'],
    experience: '10 years',
    experienceYears: 10,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: [],
    profileImage: null,
    contactEmail: 'neha@castingdesk.com',
    contactPhone: '+91 9876543214',
    isVerified: true,
    industryTypes: ['film', 'ott', 'ad_film', 'web_series'],
    connections: ['user-1'],
    dayRate: 40000,
    rating: 4.9,
    reviewCount: 55,
    createdAt: '2023-09-15T10:00:00Z',
  },
  {
    id: 'user-6',
    name: 'Siddharth Rao',
    role: 'talent',
    title: 'Sound Designer',
    crewRole: 'Sound Designer',
    bio: 'Professional sound designer and mixer with experience in Dolby Atmos and spatial audio for cinema.',
    skills: ['Sound Design', 'Mixing', 'Foley', 'ADR', 'Dolby Atmos', 'Pro Tools'],
    experience: '6 years',
    experienceYears: 6,
    location: 'Hyderabad, India',
    availability: 'available',
    portfolioLinks: ['https://soundcloud.com/sidrao'],
    profileImage: null,
    contactEmail: 'sid.rao@email.com',
    contactPhone: '+91 9876543215',
    isVerified: false,
    industryTypes: ['film', 'ott', 'ad_film'],
    connections: [],
    dayRate: 25000,
    rating: 4.5,
    reviewCount: 18,
    createdAt: '2024-04-05T10:00:00Z',
  },
  {
    id: 'user-7',
    name: 'Meera Desai',
    role: 'talent',
    title: 'Film Editor',
    crewRole: 'Editor',
    bio: 'Skilled editor with expertise in narrative pacing. Worked on 10+ feature films including 3 national award winners.',
    skills: ['Editing', 'DaVinci Resolve', 'Premiere Pro', 'Color Grading', 'Sound Sync'],
    experience: '9 years',
    experienceYears: 9,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://vimeo.com/meeraedits'],
    profileImage: null,
    contactEmail: 'meera.desai@email.com',
    contactPhone: '+91 9876543216',
    isVerified: true,
    industryTypes: ['film', 'ott', 'web_series'],
    connections: ['user-4'],
    dayRate: 45000,
    rating: 4.7,
    reviewCount: 28,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'user-8',
    name: 'Vikram Singh',
    role: 'talent',
    title: 'Screenwriter',
    crewRole: 'Writer',
    bio: 'Published screenwriter with scripts for 5 feature films and 2 OTT series. Strong in dialogue and character arcs.',
    skills: ['Screenwriting', 'Dialogue', 'Story Development', 'Script Doctoring', 'Hindi', 'English'],
    experience: '7 years',
    experienceYears: 7,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://drive.google.com/vikramscripts'],
    profileImage: null,
    contactEmail: 'vikram.writer@email.com',
    contactPhone: '+91 9876543217',
    isVerified: true,
    industryTypes: ['film', 'ott', 'theatre'],
    connections: [],
    dayRate: 30000,
    rating: 4.6,
    reviewCount: 22,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'user-9',
    name: 'Anita Kumari',
    role: 'talent',
    title: 'Lighting Director',
    crewRole: 'Lightman',
    bio: 'Expert gaffer and lighting director with deep understanding of mood lighting for film and stage. Known for innovative setups.',
    skills: ['Lighting', 'Gaffer', 'Electrical', 'LED Panels', 'Tungsten', 'HMI'],
    experience: '11 years',
    experienceYears: 11,
    location: 'Chennai, India',
    availability: 'available',
    portfolioLinks: [],
    profileImage: null,
    contactEmail: 'anita.light@email.com',
    contactPhone: '+91 9876543218',
    isVerified: false,
    industryTypes: ['film', 'ad_film', 'music_video'],
    connections: [],
    dayRate: 20000,
    rating: 4.4,
    reviewCount: 15,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'user-10',
    name: 'Deepak Malhotra',
    role: 'talent',
    title: 'Production Designer',
    crewRole: 'Production Designer',
    bio: 'Award-winning production designer specializing in period and fantasy sets. Worked on 8 feature films.',
    skills: ['Set Design', 'Art Direction', 'Period Design', 'Model Making', '3D Visualization'],
    experience: '14 years',
    experienceYears: 14,
    location: 'Mumbai, India',
    availability: 'busy',
    portfolioLinks: ['https://deepakdesigns.com'],
    profileImage: null,
    contactEmail: 'deepak.pd@email.com',
    contactPhone: '+91 9876543219',
    isVerified: true,
    industryTypes: ['film', 'ott', 'theatre'],
    connections: ['user-4'],
    dayRate: 60000,
    rating: 4.8,
    reviewCount: 35,
    createdAt: '2023-11-15T10:00:00Z',
  },
  {
    id: 'user-11',
    name: 'Fatima Khan',
    role: 'talent',
    title: 'Makeup & Prosthetics Artist',
    crewRole: 'Makeup Artist',
    bio: 'Specialist in character transformation and prosthetic makeup for film. Trained at L.A. makeup school.',
    skills: ['Makeup', 'Prosthetics', 'SFX Makeup', 'Character Design', 'Aging Techniques'],
    experience: '8 years',
    experienceYears: 8,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://instagram.com/fatimamakeup'],
    profileImage: null,
    contactEmail: 'fatima.mua@email.com',
    contactPhone: '+91 9876543220',
    isVerified: true,
    industryTypes: ['film', 'ott', 'ad_film', 'theatre'],
    connections: [],
    dayRate: 35000,
    rating: 4.7,
    reviewCount: 40,
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'user-12',
    name: 'Rajesh Nair',
    role: 'talent',
    title: 'Costume Designer',
    crewRole: 'Costume Designer',
    bio: 'Fashion-forward costume designer bridging contemporary and traditional Indian aesthetics for film.',
    skills: ['Costume Design', 'Textile Knowledge', 'Period Costuming', 'Styling', 'Tailoring'],
    experience: '10 years',
    experienceYears: 10,
    location: 'Bangalore, India',
    availability: 'available',
    portfolioLinks: ['https://rajeshnairdesigns.com'],
    profileImage: null,
    contactEmail: 'rajesh.costume@email.com',
    contactPhone: '+91 9876543221',
    isVerified: false,
    industryTypes: ['film', 'ott', 'ad_film'],
    connections: [],
    dayRate: 30000,
    rating: 4.5,
    reviewCount: 20,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'user-13',
    name: 'Aakash Patel',
    role: 'talent',
    title: 'VFX Supervisor',
    crewRole: 'VFX Artist',
    bio: 'VFX supervisor with credits on major Bollywood blockbusters. Expert in compositing, CGI, and virtual production.',
    skills: ['VFX', 'Compositing', 'CGI', 'Nuke', 'Houdini', 'Unreal Engine'],
    experience: '9 years',
    experienceYears: 9,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://vimeo.com/aakashvfx'],
    profileImage: null,
    contactEmail: 'aakash.vfx@email.com',
    contactPhone: '+91 9876543222',
    isVerified: true,
    industryTypes: ['film', 'ott', 'ad_film'],
    connections: [],
    dayRate: 55000,
    rating: 4.6,
    reviewCount: 25,
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'user-14',
    name: 'Sunita Reddy',
    role: 'talent',
    title: 'Choreographer',
    crewRole: 'Choreographer',
    bio: 'Versatile choreographer trained in Bharatanatyam, contemporary, and Bollywood dance forms. Choreographed 50+ songs.',
    skills: ['Choreography', 'Bharatanatyam', 'Contemporary', 'Hip Hop', 'Bollywood'],
    experience: '15 years',
    experienceYears: 15,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://youtube.com/sunitadance'],
    profileImage: null,
    contactEmail: 'sunita.dance@email.com',
    contactPhone: '+91 9876543223',
    isVerified: true,
    industryTypes: ['film', 'ott', 'music_video', 'theatre'],
    connections: [],
    dayRate: 45000,
    rating: 4.8,
    reviewCount: 50,
    createdAt: '2023-08-10T10:00:00Z',
  },
  {
    id: 'user-15',
    name: 'Rahul Verma',
    role: 'talent',
    title: 'Stunt Coordinator',
    crewRole: 'Stunt Coordinator',
    bio: 'International stunt coordinator with training from Hong Kong action school. Safety-first approach with spectacular results.',
    skills: ['Stunts', 'Action Choreography', 'Wire Work', 'Fight Scenes', 'Safety Coordination'],
    experience: '13 years',
    experienceYears: 13,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://youtube.com/rahulstunts'],
    profileImage: null,
    contactEmail: 'rahul.stunts@email.com',
    contactPhone: '+91 9876543224',
    isVerified: true,
    industryTypes: ['film', 'ott', 'ad_film'],
    connections: [],
    dayRate: 50000,
    rating: 4.9,
    reviewCount: 38,
    createdAt: '2023-10-01T10:00:00Z',
  },
  {
    id: 'user-16',
    name: 'Kavya Iyer',
    role: 'talent',
    title: 'Actress',
    crewRole: 'Actor',
    bio: 'National School of Drama graduate with range from comedy to intense drama. Fluent in 4 languages.',
    skills: ['Acting', 'Theatre', 'Dance', 'Hindi', 'English', 'Tamil', 'Malayalam'],
    experience: '5 years',
    experienceYears: 5,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://vimeo.com/kavyareel'],
    profileImage: null,
    contactEmail: 'kavya.iyer@email.com',
    contactPhone: '+91 9876543225',
    isVerified: false,
    industryTypes: ['film', 'ott', 'theatre', 'web_series'],
    connections: [],
    dayRate: 40000,
    rating: 4.4,
    reviewCount: 12,
    createdAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'user-17',
    name: 'Mohit Joshi',
    role: 'talent',
    title: 'Director of Photography',
    crewRole: 'Cinematographer',
    bio: 'FTII alumni specializing in naturalistic lighting. Shot 3 Cannes-selected short films and 2 features.',
    skills: ['Cinematography', 'Natural Light', 'Steadicam', 'Underwater', 'ARRI Alexa'],
    experience: '7 years',
    experienceYears: 7,
    location: 'Pune, India',
    availability: 'available',
    portfolioLinks: ['https://vimeo.com/mohitdop'],
    profileImage: null,
    contactEmail: 'mohit.dop@email.com',
    contactPhone: '+91 9876543226',
    isVerified: true,
    industryTypes: ['film', 'ad_film'],
    connections: [],
    dayRate: 55000,
    rating: 4.7,
    reviewCount: 19,
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'user-18',
    name: 'Zara Sheikh',
    role: 'talent',
    title: 'Film Director',
    crewRole: 'Director',
    bio: 'Award-winning director known for socially conscious narratives. Debut feature won 3 national awards.',
    skills: ['Direction', 'Script Analysis', 'Actor Direction', 'Visual Storytelling', 'Hindi', 'Urdu'],
    experience: '10 years',
    experienceYears: 10,
    location: 'Mumbai, India',
    availability: 'busy',
    portfolioLinks: ['https://vimeo.com/zaradirects'],
    profileImage: null,
    contactEmail: 'zara.director@email.com',
    contactPhone: '+91 9876543227',
    isVerified: true,
    industryTypes: ['film', 'ott', 'web_series'],
    connections: ['user-4'],
    dayRate: 80000,
    rating: 4.9,
    reviewCount: 42,
    createdAt: '2023-07-01T10:00:00Z',
  },
  {
    id: 'user-19',
    name: 'Karan Bhatia',
    role: 'talent',
    title: 'Gaffer & Lightman',
    crewRole: 'Lightman',
    bio: 'Experienced gaffer handling large-scale film lighting setups. Expert in both indoor and outdoor environments.',
    skills: ['Lighting', 'Grip', 'Generator Operation', 'LED Systems', 'Power Distribution'],
    experience: '8 years',
    experienceYears: 8,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: [],
    profileImage: null,
    contactEmail: 'karan.light@email.com',
    contactPhone: '+91 9876543228',
    isVerified: false,
    industryTypes: ['film', 'ott', 'ad_film'],
    connections: [],
    dayRate: 15000,
    rating: 4.3,
    reviewCount: 11,
    createdAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'user-20',
    name: 'Tara Menon',
    role: 'talent',
    title: 'Screenwriter',
    crewRole: 'Writer',
    bio: 'Emmy-nominated writer for Hindi OTT series. Specializes in thriller and crime genres.',
    skills: ['Screenwriting', 'Show Running', 'Thriller', 'Crime Genre', 'English', 'Hindi'],
    experience: '12 years',
    experienceYears: 12,
    location: 'Mumbai, India',
    availability: 'available',
    portfolioLinks: ['https://taramenon.com'],
    profileImage: null,
    contactEmail: 'tara.writer@email.com',
    contactPhone: '+91 9876543229',
    isVerified: true,
    industryTypes: ['film', 'ott', 'web_series'],
    connections: [],
    dayRate: 50000,
    rating: 4.8,
    reviewCount: 30,
    createdAt: '2023-12-01T10:00:00Z',
  },
];

export const SAMPLE_CASTING_CALLS: CastingCall[] = [
  {
    id: 'cc-1',
    title: 'Lead Male Actor for Period Drama',
    description: 'Seeking a versatile actor aged 28-35 for the lead role in an upcoming period drama set in 1947 India. Must be comfortable with intense emotional scenes and period dialect.',
    roleNeeded: 'Lead Actor',
    projectType: 'film',
    projectName: 'The Last Monsoon',
    location: 'Mumbai, India',
    compensation: 'As per industry standards',
    deadline: '2026-04-15T00:00:00Z',
    postedBy: 'user-4',
    postedByName: 'Kavita Productions',
    postedByVerified: true,
    skillsRequired: ['Acting', 'Hindi', 'Dialogue Delivery', 'Horse Riding'],
    experienceLevel: '5+ years',
    status: 'open',
    applicantCount: 24,
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'cc-2',
    title: 'Cinematographer for OTT Series',
    description: 'Looking for an experienced cinematographer for an 8-episode thriller series. Must have experience with low-light shooting and handheld work.',
    roleNeeded: 'Cinematographer',
    projectType: 'ott',
    projectName: 'Shadows Within',
    location: 'Delhi & Jaipur',
    compensation: 'Competitive package',
    deadline: '2026-03-30T00:00:00Z',
    postedBy: 'user-5',
    postedByName: 'Neha Agarwal',
    postedByVerified: true,
    skillsRequired: ['Cinematography', 'Low-light', 'Handheld', 'ARRI'],
    experienceLevel: '8+ years',
    status: 'open',
    applicantCount: 12,
    createdAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'cc-3',
    title: 'Supporting Actress for Ad Film',
    description: 'Casting for a supporting role in a premium automobile brand ad. Looking for someone aged 25-30 with a natural, modern look.',
    roleNeeded: 'Supporting Actress',
    projectType: 'ad_film',
    projectName: 'Brand Campaign',
    location: 'Goa, India',
    compensation: '2-3L per day',
    deadline: '2026-03-20T00:00:00Z',
    postedBy: 'user-5',
    postedByName: 'Neha Agarwal',
    postedByVerified: true,
    skillsRequired: ['Acting', 'Modeling', 'English'],
    experienceLevel: '2+ years',
    status: 'open',
    applicantCount: 56,
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'cc-4',
    title: 'Editor for Web Series',
    description: 'Need a skilled editor for a 6-episode web series. Proficiency in DaVinci Resolve or Premiere Pro required. Fast turnaround needed.',
    roleNeeded: 'Editor',
    projectType: 'web_series',
    projectName: 'City Lights',
    location: 'Remote',
    compensation: 'Per episode basis',
    deadline: '2026-04-01T00:00:00Z',
    postedBy: 'user-4',
    postedByName: 'Kavita Productions',
    postedByVerified: true,
    skillsRequired: ['Editing', 'DaVinci Resolve', 'Color Grading', 'Sound Sync'],
    experienceLevel: '3+ years',
    status: 'open',
    applicantCount: 18,
    createdAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'cc-5',
    title: 'Fresh Faces for Theatre Production',
    description: 'Open audition for a contemporary Hindi play. Looking for actors aged 20-40 with theatre background. No prior film experience needed.',
    roleNeeded: 'Theatre Actor',
    projectType: 'theatre',
    projectName: 'Rang Manch',
    location: 'Delhi, India',
    compensation: 'Monthly stipend + performance bonus',
    deadline: '2026-05-01T00:00:00Z',
    postedBy: 'user-5',
    postedByName: 'Neha Agarwal',
    postedByVerified: true,
    skillsRequired: ['Theatre', 'Hindi', 'Stage Presence', 'Improvisation'],
    experienceLevel: 'Open to freshers',
    status: 'open',
    applicantCount: 42,
    createdAt: '2026-02-20T10:00:00Z',
  },
];

export const SAMPLE_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'user-5',
    participantName: 'Neha Agarwal',
    participantRole: 'casting_director',
    participantImage: null,
    participantVerified: true,
    lastMessage: 'We would like to schedule your audition for next week.',
    lastMessageTime: '2026-02-22T09:30:00Z',
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    participantId: 'user-4',
    participantName: 'Kavita Productions',
    participantRole: 'producer',
    participantImage: null,
    participantVerified: true,
    lastMessage: 'Thank you for your application. We are reviewing your portfolio.',
    lastMessageTime: '2026-02-21T16:45:00Z',
    unreadCount: 0,
  },
  {
    id: 'conv-3',
    participantId: 'user-3',
    participantName: 'Rohan Kapoor',
    participantRole: 'talent',
    participantImage: null,
    participantVerified: false,
    lastMessage: 'Would love to collaborate on the short film project!',
    lastMessageTime: '2026-02-20T14:20:00Z',
    unreadCount: 1,
  },
];

export const SAMPLE_MESSAGES: Record<string, Message[]> = {
  'conv-1': [
    { id: 'msg-1', senderId: 'user-5', receiverId: 'me', content: 'Hi! I saw your profile and I think you would be great for the period drama we are casting.', timestamp: '2026-02-21T10:00:00Z', read: true },
    { id: 'msg-2', senderId: 'me', receiverId: 'user-5', content: 'Thank you! I would love to learn more about the role and project.', timestamp: '2026-02-21T10:15:00Z', read: true },
    { id: 'msg-3', senderId: 'user-5', receiverId: 'me', content: 'The project is a feature film set in pre-independence India. The lead role requires strong emotional range.', timestamp: '2026-02-21T11:00:00Z', read: true },
    { id: 'msg-4', senderId: 'me', receiverId: 'user-5', content: 'That sounds incredibly exciting. I have experience with period dramas and would be very interested.', timestamp: '2026-02-21T11:30:00Z', read: true },
    { id: 'msg-5', senderId: 'user-5', receiverId: 'me', content: 'We would like to schedule your audition for next week.', timestamp: '2026-02-22T09:30:00Z', read: false },
  ],
  'conv-2': [
    { id: 'msg-6', senderId: 'me', receiverId: 'user-4', content: 'Hello, I applied for the Editor role for City Lights. Looking forward to hearing from you.', timestamp: '2026-02-20T14:00:00Z', read: true },
    { id: 'msg-7', senderId: 'user-4', receiverId: 'me', content: 'Thank you for your application. We are reviewing your portfolio.', timestamp: '2026-02-21T16:45:00Z', read: true },
  ],
  'conv-3': [
    { id: 'msg-8', senderId: 'user-3', receiverId: 'me', content: 'Hey! I noticed you are also based in Mumbai. I am working on a short film and looking for collaborators.', timestamp: '2026-02-20T13:00:00Z', read: true },
    { id: 'msg-9', senderId: 'me', receiverId: 'user-3', content: 'That sounds interesting! What genre is the short film?', timestamp: '2026-02-20T13:45:00Z', read: true },
    { id: 'msg-10', senderId: 'user-3', receiverId: 'me', content: 'Would love to collaborate on the short film project!', timestamp: '2026-02-20T14:20:00Z', read: false },
  ],
};

export const SAMPLE_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    castingCallId: 'cc-1',
    castingCallTitle: 'Lead Male Actor for Period Drama',
    applicantId: 'me',
    applicantName: 'You',
    status: 'shortlisted',
    appliedAt: '2026-02-12T10:00:00Z',
    note: 'Strong audition tape submitted',
  },
  {
    id: 'app-2',
    castingCallId: 'cc-4',
    castingCallTitle: 'Editor for Web Series',
    applicantId: 'me',
    applicantName: 'You',
    status: 'applied',
    appliedAt: '2026-02-19T14:00:00Z',
    note: '',
  },
];

export const MY_PROFILE: UserProfile = {
  id: 'me',
  name: 'Alex Rivera',
  role: 'talent',
  title: 'Actor & Filmmaker',
  crewRole: 'Actor',
  bio: 'Passionate about storytelling through cinema. Trained in method acting with experience across feature films, OTT series, and theatre productions.',
  skills: ['Acting', 'Direction', 'Screenwriting', 'Hindi', 'English', 'Tamil'],
  experience: '6 years',
  experienceYears: 6,
  location: 'Mumbai, India',
  availability: 'available',
  portfolioLinks: ['https://youtube.com/alexrivera', 'https://vimeo.com/alexreel'],
  profileImage: null,
  contactEmail: 'alex.rivera@email.com',
  contactPhone: '+91 9876543200',
  isVerified: true,
  industryTypes: ['film', 'ott', 'theatre'],
  connections: ['user-1', 'user-4', 'user-5'],
  dayRate: 45000,
  rating: 4.6,
  reviewCount: 24,
  createdAt: '2023-11-01T10:00:00Z',
};

export const ROLE_LABELS: Record<string, string> = {
  talent: 'Talent',
  producer: 'Producer',
  casting_director: 'Casting Director',
};

export const INDUSTRY_LABELS: Record<string, string> = {
  film: 'Film',
  ott: 'OTT',
  ad_film: 'Ad Film',
  theatre: 'Theatre',
  music_video: 'Music Video',
  web_series: 'Web Series',
};

export const AVAILABILITY_LABELS: Record<string, string> = {
  available: 'Available',
  busy: 'Busy',
  not_available: 'Not Available',
};
